networks:
  board:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  backend:
    restart: unless-stopped
    image: ghcr.io/uni-board/backend:0.0.1-snapshot
    environment:
      DB_CONNECT: mongodb://10.5.0.3:27017 # required(if NO_DB=false), connect url to MongoDB
      SOCKETS_ENABLED: "true" # optional, Sockets API
      NO_DB: "false" # optional, if true, uses in-memory db, otherwise uses MongoDB
      TRACE: "true" # optional, if true, writes all logs, system will be slower
    ports:
      - 80:8080 # API
      - 81:8081 # Sockets
    networks:
      board:
        ipv4_address: 10.5.0.2
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      board:
        ipv4_address: 10.5.0.3
    volumes:
      - ./db:/data/db

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  pdf-converter:
    build: ./pdf-converter
    restart: unless-stopped
    environment:
      NODE_ENV: production
      API_URL: http://10.5.0.2:8080
    ports:
      - 3021:3021
    networks:
      board:
        ipv4_address: 10.5.0.4
    depends_on:
      - backend